version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mapeia a porta do container para o host
    volumes:
      - .:/app # Permite edição local e recarregamento
    environment:
      - GIN_MODE=release # Configura o modo do Gin
