name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout o código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configurar Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # Instalar dependências do backend
      - name: Install Backend Dependencies
        run: |
          cd backend
          go mod tidy

      # Testar o backend
      - name: Test Backend
        run: |
          cd backend
          go test ./...

      # Testar e construir o frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Simular o deploy (ajuste conforme necessário para seu provedor real)
      - name: Deploy Frontend
        run: |
          echo "Deploying frontend..."
          ls -l frontend/build

      - name: Deploy Backend
        run: |
          echo "Deploying backend..."
          cd backend
          echo "Backend deployed to production"
