name: CI/CD for Go API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test API
    runs-on: ubuntu-latest  # Corrigido para um ambiente válido

    steps:
      # 1. Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar o Go no ambiente
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2 # Substitua pela versão do Go que você está usando

      # 3. Instalar dependências e compilar o código
      - name: Install dependencies
        run: |
          cd backend  
          go mod tidy
          go mod download

      # 4. Executar os testes
      - name: Run tests
        run: |
          cd backend  
          go test ./... -v

      # 5. Verificar formatação e lint do código (opcional)
      - name: Run lint and format checks
        run: |
          cd backend  
          go fmt ./...
          go vet ./...

  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar o Go no ambiente
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # 3. Instalar dependências
      - name: Install dependencies
        run: |
          cd backend  
          go mod tidy
          go mod download

      # 4. Build da aplicação
      - name: Build API
        run: |
          cd backend 
          go build -o app .
